### ISSUE TITLE
Issue when field on row next to another field

### ISSUE THREAD

**Issue by Notanotherdotcom** [Toutouwai/InputfieldSelectImages#5]
Hi, fantastic module I wish I'd found sooner :)

I'm using this in a template next to a textarea field and I'm using it to select one image from a few image fields elsewhere on the page. 

The textarea field it sits next to is at 50% width, as is this field. When I click to select an image, the image list slides out, but when I select one the height stays stretched on the field next to it.

So this is fine and you can see the content field below it:

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/190857/151041439-50117fe7-708d-4955-9474-3519125fd7fe.png">

But after selecting an image the fields don't shrink back down vertically:

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/190857/151041585-7671824a-e2e8-4479-9f1d-775aba2dcb7e.png">

Seems like the field next door to it gets a min-height set and I'm not sure how to clear it for all fields in the same row.

**Comment by Toutouwai** [comment]
I can't reproduce that here - the inputfield height is shrinking as expected after an image is selected.

![test-select-images](https://user-images.githubusercontent.com/1538852/151060956-ee079a79-8c2b-42e2-86a8-ec97e801766a.gif)

Are you using AdminThemeUikit? The old legacy themes use some crazy JS to try and set and align inputfield heights. If you're using one of those old themes then this would be a bug with the theme. AdminThemeUikit is a more modern and uses a flexbox layout.

**Comment by Toutouwai** [comment]
Hang on, I can reproduce it intermittently. It's tricky to investigate because if the browser window dimensions change (e.g. opening dev tools) or if I use the inspector arrow the field then collapses to it's correct height. Will try and find out what's going on and report back.

**Comment by Toutouwai** [comment]
The issue is due to a buggy match height function in Uikit. The core itself tries to hack around the problem, e.g. [here](https://github.com/processwire/processwire/blob/400399ce60960f5477e90cc1bb4be05546be7e5e/wire/modules/AdminTheme/AdminThemeUikit/scripts/main.js#L33-L37).

I've attempted to work around the problem in v0.1.5 by using `hide()` instead of `slideUp()` and it seems to have fixed it here, but it's hard to be sure because the issue is intermittent.

Please let me know if this resolves the issue for you. If it doesn't then I suggest adding `.InputfieldContent { min-height:initial !important; }` in some custom admin CSS because I can't see any reason why this Uikit min-height manipulation is even necessary for a flexbox layout. The layout works perfectly well without it. But I don't want to add such generic CSS in the module itself.

**Comment by Notanotherdotcom** [comment]
Perfect, thank you that works. 

I did try and see if there was a way to do it with JS before posting the issue but when I set the height shorter while the animation was running it went very buggy so I think this is the best solution.
