### ISSUE TITLE
Composer installation support

### ISSUE THREAD

**Issue by teppokoivula** [Toutouwai/InputfieldSelectImages#7]
Hey Robin,

Since this module is often used together with FieldtypeDynamicOptions, which can already be installed via composer, it would be very nice if this module also had support for that. Thanks for considering! :)

**Comment by Toutouwai** [comment]
Hi Teppo, I've added Composer support.

**Comment by teppokoivula** [comment]
Thank you!

**Comment by elabx** [comment]
Hi! I wonder, is it normal for this to require `processwire/processwire` as a dependency? Because it ends up installing ProcessWire in the vendor folder but as we are all aware this is useless in the context of how ProcessWire loads composer libraries?? Unless ProcessWire had it's composer installer right? 

Thanks for this wonder plugin!

**Comment by Toutouwai** [comment]
@elabx, I don't know what's normal for composer.json in the case of PW modules because I don't use Composer to install modules. I just followed the example of Teppo's modules, e.g. https://github.com/wireframe-framework/Wireframe/blob/master/composer.json
Hopefully @teppokoivula will reply to explain more.
